name: Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule:
    - cron: "0 0 7,14 * *"

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    env:
      ASDF_OP_DEBUG: true
      CI: true
    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: please --version
